### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by Sunshine168** [nitin42/react-imgpro#19]
* Use greenlet or others integrating workers lib
 * use jimp implement filter params on https://github.com/picturepan2/instagram.css/tree/master/src
 * more

**Comment by Sunshine168** [comment]
## Follow Up

- [ ] Use greenlet or others integrating workers lib
- [ ] use jimp implement filter params on picturepan2/instagram.css:src@master
- [ ] Convert React new life cycle Api
- [x] Updated Webpack to v4 and babel to v7

**Comment by Sunshine168** [comment]
for now ,  i cant use jimp implement filter params on picturepan2/instagram.css:src@master,   if any help or suggestion  will be appreciated

**Comment by jarvisluong** [comment]
Is it possible to use web assembly to improve the performance? I found a good candidate: https://github.com/KnicKnic/WASM-ImageMagick

Would love to make a PR for this

**Comment by Sunshine168** [comment]
PR is always welcome , but before , we should deep thinking about [WASM-ImageMagick] can cover the old feature otherwise making a new lib or separate the processor as a plugin will be better =，=
